In [3]:
# Import models and utility functions
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, learning_curve
from sklearn.metrics import mean_squared_error as MSE
from sklearn.metrics import roc_auc_score, accuracy_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns


# ignore warning
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# import data
file = 'fraud.csv'
df = pd.read_csv(file)
print(df.columns)
df = df.rename(columns={'oldbalanceOrg': 'Old_Balance_Orig',
                        'newbalanceOrig': 'New_Balance_Orig',
                        'oldbalanceDest': 'Old_Balance_Dest',
                        'newbalanceDest': 'New_Balance_Dest',
                        'nameOrig': 'Name_Orig',
                        'nameDest': 'Name_Dest'})
print(df.head())
print(df.info())




# EDA
print('\n The types of fraudulent transactions are {}'.format(
    list(df.loc[df.isFraud == 1].type.drop_duplicates().values)))
#
print(df.shape)
#df = df.loc[(df.isFraud!=1)&(df.amount!=0)]

print(df.shape)

"""
dfFraudTransfer = df.loc[(df.isFraud == 1) & (df.type == 'TRANSFER')]
dfFraudCashout = df.loc[(df.isFraud == 1) & (df.type == 'CASH_OUT')]

print('\n No.fraudulent in TRANSFERs = {}'.
      format(len(dfFraudTransfer)))
# The Number of

print('\n No.fraudulent in CASH_OUTs = {}'.
      format(len(dfFraudCashout)))

# data import and cleaning
X = df.loc[(df.type == 'TRANSFER')]
#X = df.loc[(df.type == 'CASH_OUT')]
y = X['isFraud']
del X['isFraud']

# Eliminate columns shown to be irrelevant for analysis in the EDA
X = X.drop(['Name_Orig', 'Name_Dest', 'isFlaggedFraud', 'type'], axis=1)
print(X.head())

# decision tree model
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2)

#X_train, X_test, y_train, y_test = train_test_split(
#    X, y, test_size=0.2, random_state=1)

dt = DecisionTreeClassifier(max_depth=5, random_state=1)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
acc = accuracy_score(y_test, y_pred)
"""

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')
   step      type    amount    Name_Orig  Old_Balance_Orig  New_Balance_Orig  \
0     1   PAYMENT   9839.64  C1231006815          170136.0         160296.36   
1     1   PAYMENT   1864.28  C1666544295           21249.0          19384.72   
2     1  TRANSFER    181.00  C1305486145             181.0              0.00   
3     1  CASH_OUT    181.00   C840083671             181.0              0.00   
4     1   PAYMENT  11668.14  C2048537720           41554.0          29885.86   

     Name_Dest  Old_Balance_Dest  New_Balance_Dest  isFraud  isFlaggedFraud  
0  M1979787155               0.0               0.0        0               0  
1  M2044282225               0.0               0.0        0               0  
2   C553264065               0.0               0.0        1               0  
3    C3899701

"\ndfFraudTransfer = df.loc[(df.isFraud == 1) & (df.type == 'TRANSFER')]\ndfFraudCashout = df.loc[(df.isFraud == 1) & (df.type == 'CASH_OUT')]\n\nprint('\n No.fraudulent in TRANSFERs = {}'.\n      format(len(dfFraudTransfer)))\n# The Number of\n\nprint('\n No.fraudulent in CASH_OUTs = {}'.\n      format(len(dfFraudCashout)))\n\n# data import and cleaning\nX = df.loc[(df.type == 'TRANSFER')]\n#X = df.loc[(df.type == 'CASH_OUT')]\ny = X['isFraud']\ndel X['isFraud']\n\n# Eliminate columns shown to be irrelevant for analysis in the EDA\nX = X.drop(['Name_Orig', 'Name_Dest', 'isFlaggedFraud', 'type'], axis=1)\nprint(X.head())\n\n# decision tree model\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2)\n\n#X_train, X_test, y_train, y_test = train_test_split(\n#    X, y, test_size=0.2, random_state=1)\n\ndt = DecisionTreeClassifier(max_depth=5, random_state=1)\ndt.fit(X_train, y_train)\ny_pred = dt.predict(X_test)\nacc = accuracy_score(y_test, y_pred)\n"

In [13]:
print(df.shape)
print(df.loc[(df.amount!=0)|(df.isFraud!=1)].shape)

print(df.loc[(df.isFraud==1) & (df.amount==0)].shape)


#删除在isFraud=1的情况下，Old_Balance_Orig<amount
print(df.shape)
print('isFraud=1的情况下，Old_Balance_Orig<amount',df.loc[(df.isFraud==1)& (df.Old_Balance_Orig<df.amount)].shape)
#print(df.loc[(df.isFraud==1)& (df.Old_Balance_Orig<df.amount)].index)
a = df.drop(df.loc[(df.isFraud==1)& (df.Old_Balance_Orig<df.amount)].index)
print(df.shape,a.shape,df.shape[0]-a.shape[0] )

df.head()

(6362620, 11)
(6362604, 11)
(16, 11)
(6362620, 11)
isFraud=1的情况下，Old_Balance_Orig<amount (29, 11)
(6362620, 11) (6362591, 11) 29


step      type    amount    Name_Orig  Old_Balance_Orig  New_Balance_Orig  \
0     1   PAYMENT   9839.64  C1231006815          170136.0         160296.36   
1     1   PAYMENT   1864.28  C1666544295           21249.0          19384.72   
2     1  TRANSFER    181.00  C1305486145             181.0              0.00   
3     1  CASH_OUT    181.00   C840083671             181.0              0.00   
4     1   PAYMENT  11668.14  C2048537720           41554.0          29885.86   

     Name_Dest  Old_Balance_Dest  New_Balance_Dest  isFraud  isFlaggedFraud  
0  M1979787155               0.0               0.0        0               0  
1  M2044282225               0.0               0.0        0               0  
2   C553264065               0.0               0.0        1               0  
3    C38997010           21182.0               0.0        1               0  
4  M1230701703               0.0               0.0        0               0

In [51]:
print('size of X_train, X_test, y_train, y_test')
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

acc = accuracy_score(y_test, y_pred)
print('accuracy of decision tree result',acc)

size of X_train, X_test, y_train, y_test
(426327, 6) (106582, 6) (426327,) (106582,)
accuracy of decision tree result 0.9998029686063312


In [52]:
from sklearn.metrics import f1_score

print('F1 macro score')
print(f1_score(y_test, y_pred, average='macro')  )
print('F1 micro score')
print(f1_score(y_test, y_pred, average='micro')  )

F1 macro score
0.9935751309133148
F1 micro score
0.9998029686063312


In [53]:
#confusion matrix of decision tree result with .2 random test dataset
from sklearn.metrics import confusion_matrix
print('confusion matrix of decision tree with .2 random test data:')
print(confusion_matrix(y_test, y_pred))


confusion matrix of decision tree with .2 random test data:
[[105748      7]
 [    14    813]]


# Cross validation accuracy score wiht cv = 5

In [27]:
#Cross validation accuracy score wiht cv = 5
from sklearn.model_selection import cross_val_score
clf = DecisionTreeClassifier(max_depth=2, random_state=1)
scores = cross_val_score(clf, X_train, y_train, cv=5)
print('Cross validation confisuion matrix wiht cv = 5')
print([s for s in scores])

Cross validation confisuion matrix wiht cv = 5
[0.9998006239298196, 0.9997771679215631, 0.9997654399174348, 0.9996364276080455, 0.9997888909739163]


#  Cross validation confisuion matrix wiht cv = 5


In [43]:
#Cross validation confisuion matrix wiht cv = 5
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf, X_train, y_train,cv=5)
conf_mat = confusion_matrix(y_pred,y_train)
print('Cross validation confisuion matrix wiht cv = 5')
print(conf_mat)
print(y_pred)

Cross validation confisuion matrix wiht cv = 5
[[422976     26]
 [    88   3237]]


# Adaboost decision tree depth = 5

In [54]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
bdt = AdaBoostClassifier(DecisionTreeClassifier(max_depth=5),
                         algorithm="SAMME",
                         n_estimators=20)

bdt.fit(X, y)

scores = cross_val_score(bdt, X_train, y_train, cv=5)
print('Cross validation confisuion matrix wiht cv = 5')
print([s for s in scores])

Cross validation confisuion matrix wiht cv = 5
[0.9998475359463327, 0.9999296319752304, 0.9998827185832405, 0.9999179030082683, 0.9999648155749722]


In [59]:
from sklearn.model_selection import cross_val_predict
b = time()
y_pred = cross_val_predict(bdt, X_train, y_train,cv=5)
conf_mat = confusion_matrix(y_train,y_pred)
print('Cross validation confisuion matrix wiht cv = 5')
print(conf_mat)
print('tims cost', time()- b)

Cross validation confisuion matrix wiht cv = 5
[[423044     13]
 [    26   3244]]
tims cost 140.29813432693481


# logistic regression

In [65]:
from sklearn import linear_model
from time import time
clf = linear_model.LogisticRegression()

b = time()
clf.fit(X_train,y_train)
print('train time cost', time()- b)

b = time()
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('accuracy of decision tree result',acc)
print('predict time cost', time()- b)

a = time()
print('confusion matrix of logistic regression with .2 random test data:')
print(confusion_matrix(y_test, y_pred))
print('tims cost', time()- a)

train time cost 2.43247389793396
accuracy of decision tree result 0.9994745829502167
predict time cost 0.010970354080200195
confusion matrix of logistic regression with .2 random test data:
[[105708     47]
 [     9    818]]
tims cost 0.08178234100341797


# L1 logistic regression

In [63]:
from sklearn import linear_model
from time import time
clf = linear_model.LogisticRegression(C=1.0, penalty='l1', tol=1e-6)

b = time()
clf.fit(X_train,y_train)
print('train time cost', time()- b)

b = time()
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('accuracy of decision tree result',acc)
print('predict time cost', time()- b)

a = time()
print('confusion matrix of L1 logistic regression with .2 random test data:')
print(confusion_matrix(y_test, y_pred))
print('tims cost', time()- a)


train time cost 19.88284468650818
accuracy of decision tree result 0.9986207802443189
predict time cost 0.0139617919921875
confusion matrix of L1 logistic regression with .2 random test data:
[[105739     16]
 [   131    696]]
tims cost 0.08377599716186523


# L1 logistic regression CV5

In [55]:
from sklearn import linear_model
from time import time
clf = linear_model.LogisticRegression(C=1.0, penalty='l1', tol=1e-6)
a = time()
scores = cross_val_score(clf, X_train, y_train, cv=5)
print('tims cost', time()- a)
print('Cross validation confisuion matrix wiht cv = 5')
print([s for s in scores])




Cross validation confisuion matrix wiht cv = 5
[0.9987920155747895, 0.9986630075293786, 0.9987099044156453, 0.9988271858324048, 0.9984167008737466]
